# Generated by Django 3.2.13 on 2022-05-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='semester',
        ),
        migrations.AddField(
            model_name='student',
            name='Car',
            field=models.CharField(choices=[('1', 'Volvo'), ('2', 'Saab'), ('3', 'Opel'), ('4', 'Audi'), ('5', 'hyundai'), ('6', 'suzuki')], default='1', max_length=20),
        ),
    ]
