# Generated by Django 3.2.13 on 2022-05-23 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220523_0642'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Car',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='Car',
            new_name='Car_name',
        ),
    ]
